# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIControlador.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaInicio(object):
    def setupUi(self, VentanaInicio):
        VentanaInicio.setObjectName("VentanaInicio")
        VentanaInicio.resize(407, 457)
        self.label_2 = QtWidgets.QLabel(VentanaInicio)
        self.label_2.setGeometry(QtCore.QRect(80, 300, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(VentanaInicio)
        self.label_3.setGeometry(QtCore.QRect(80, 340, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.boton_automatico = QtWidgets.QPushButton(VentanaInicio)
        self.boton_automatico.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.boton_automatico.setObjectName("boton_automatico")
        self.boton_manual = QtWidgets.QPushButton(VentanaInicio)
        self.boton_manual.setGeometry(QtCore.QRect(110, 30, 75, 23))
        self.boton_manual.setObjectName("boton_manual")
        self.boton_salir = QtWidgets.QPushButton(VentanaInicio)
        self.boton_salir.setGeometry(QtCore.QRect(330, 430, 75, 23))
        self.boton_salir.setObjectName("boton_salir")
        self.label_4 = QtWidgets.QLabel(VentanaInicio)
        self.label_4.setGeometry(QtCore.QRect(80, 420, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(VentanaInicio)
        self.label_5.setGeometry(QtCore.QRect(80, 380, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(VentanaInicio)
        self.label_7.setGeometry(QtCore.QRect(130, 190, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(VentanaInicio)
        self.label.setGeometry(QtCore.QRect(0, 260, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(VentanaInicio)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(VentanaInicio)
        self.label_9.setGeometry(QtCore.QRect(30, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_estado = QtWidgets.QLabel(VentanaInicio)
        self.label_estado.setGeometry(QtCore.QRect(230, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_estado.setFont(font)
        self.label_estado.setText("")
        self.label_estado.setObjectName("label_estado")
        self.label_11 = QtWidgets.QLabel(VentanaInicio)
        self.label_11.setGeometry(QtCore.QRect(130, 160, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(VentanaInicio)
        self.label_12.setGeometry(QtCore.QRect(130, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(VentanaInicio)
        self.label_13.setGeometry(QtCore.QRect(130, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.text_posicion = QtWidgets.QTextEdit(VentanaInicio)
        self.text_posicion.setGeometry(QtCore.QRect(0, 180, 121, 31))
        self.text_posicion.setObjectName("text_posicion")
        self.text_kd = QtWidgets.QTextEdit(VentanaInicio)
        self.text_kd.setGeometry(QtCore.QRect(0, 150, 121, 31))
        self.text_kd.setObjectName("text_kd")
        self.text_ki = QtWidgets.QTextEdit(VentanaInicio)
        self.text_ki.setGeometry(QtCore.QRect(0, 120, 121, 31))
        self.text_ki.setObjectName("text_ki")
        self.text_kp = QtWidgets.QTextEdit(VentanaInicio)
        self.text_kp.setGeometry(QtCore.QRect(0, 90, 121, 31))
        self.text_kp.setObjectName("text_kp")
        self.label_text = QtWidgets.QLabel(VentanaInicio)
        self.label_text.setGeometry(QtCore.QRect(230, 110, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_text.setFont(font)
        self.label_text.setText("")
        self.label_text.setObjectName("label_text")
        self.label_14 = QtWidgets.QLabel(VentanaInicio)
        self.label_14.setGeometry(QtCore.QRect(220, 70, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_velocidad = QtWidgets.QLabel(VentanaInicio)
        self.label_velocidad.setGeometry(QtCore.QRect(10, 300, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_velocidad.setFont(font)
        self.label_velocidad.setObjectName("label_velocidad")
        self.label_posicion = QtWidgets.QLabel(VentanaInicio)
        self.label_posicion.setGeometry(QtCore.QRect(10, 340, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_posicion.setFont(font)
        self.label_posicion.setObjectName("label_posicion")
        self.label_corriente = QtWidgets.QLabel(VentanaInicio)
        self.label_corriente.setGeometry(QtCore.QRect(10, 380, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_corriente.setFont(font)
        self.label_corriente.setObjectName("label_corriente")
        self.label_voltaje = QtWidgets.QLabel(VentanaInicio)
        self.label_voltaje.setGeometry(QtCore.QRect(10, 420, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_voltaje.setFont(font)
        self.label_voltaje.setObjectName("label_voltaje")
        self.boton_on = QtWidgets.QPushButton(VentanaInicio)
        self.boton_on.setGeometry(QtCore.QRect(0, 220, 75, 23))
        self.boton_on.setObjectName("boton_on")
        self.boton_off = QtWidgets.QPushButton(VentanaInicio)
        self.boton_off.setGeometry(QtCore.QRect(80, 220, 75, 23))
        self.boton_off.setObjectName("boton_off")

        self.retranslateUi(VentanaInicio)
        self.boton_salir.clicked.connect(VentanaInicio.close)
        QtCore.QMetaObject.connectSlotsByName(VentanaInicio)

    def retranslateUi(self, VentanaInicio):
        _translate = QtCore.QCoreApplication.translate
        VentanaInicio.setWindowTitle(_translate("VentanaInicio", "ControladorMotor "))
        self.label_2.setText(_translate("VentanaInicio", "Velocidad"))
        self.label_3.setText(_translate("VentanaInicio", "Posicion"))
        self.boton_automatico.setText(_translate("VentanaInicio", "Automático"))
        self.boton_manual.setText(_translate("VentanaInicio", "Manual"))
        self.boton_salir.setText(_translate("VentanaInicio", "Salir"))
        self.label_4.setText(_translate("VentanaInicio", "Voltaje"))
        self.label_5.setText(_translate("VentanaInicio", "Corriente"))
        self.label_7.setText(_translate("VentanaInicio", "Posicion"))
        self.label.setText(_translate("VentanaInicio", "Datos Recibidos"))
        self.label_8.setText(_translate("VentanaInicio", "Enviar Datos"))
        self.label_9.setText(_translate("VentanaInicio", "Modo de Operacion"))
        self.label_11.setText(_translate("VentanaInicio", "kd"))
        self.label_12.setText(_translate("VentanaInicio", "ki"))
        self.label_13.setText(_translate("VentanaInicio", "kp"))
        self.label_14.setText(_translate("VentanaInicio", "Datos del I2C eco"))
        self.label_velocidad.setText(_translate("VentanaInicio", "0"))
        self.label_posicion.setText(_translate("VentanaInicio", "0"))
        self.label_corriente.setText(_translate("VentanaInicio", "0"))
        self.label_voltaje.setText(_translate("VentanaInicio", "0"))
        self.boton_on.setText(_translate("VentanaInicio", "Motor ON"))
        self.boton_off.setText(_translate("VentanaInicio", "Motor OFF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaInicio = QtWidgets.QWidget()
    ui = Ui_VentanaInicio()
    ui.setupUi(VentanaInicio)
    VentanaInicio.show()
    sys.exit(app.exec_())

